error: lint `clippy::safe_fn` has been renamed to `clippy::safe_code`
   |
   = help: use the new name `clippy::safe_code`
   = note: requested on the command line with `-D clippy::safe_fn`
   = note: `-D renamed-and-removed-lints` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(renamed_and_removed_lints)]`

error: lint `clippy::safe_fn` has been renamed to `clippy::safe_code`
   |
   = help: use the new name `clippy::safe_code`
   = note: requested on the command line with `-D clippy::safe_fn`
   = note: duplicate diagnostic emitted due to `-Z deduplicate-diagnostics=no`

error: item must be `pub`
  --> tests/ui/iterator_step_by_zero.rs:3:1
   |
LL | fn main() {
   | ^ help: make this item public: `pub`
   |
   = note: requested on the command line with `-D clippy::missing-pub`

error: function must be `unsafe`
  --> tests/ui/iterator_step_by_zero.rs:3:1
   |
LL | fn main() {
   | ^
   |
help: make this function unsafe: `unsafe`
  --> tests/ui/iterator_step_by_zero.rs:3:1
   |
LL | fn main() {
   | ^
   = note: `-D clippy::safe-code` implied by `-D clippy::safe-fn`
   = help: to override `-D clippy::safe-fn` add `#[allow(clippy::safe_code)]`

error: variable must be `mut`
  --> tests/ui/iterator_step_by_zero.rs:14:9
   |
LL |     let y = NotIterator;
   |         ^ help: make this variable mutable: `mut`
   |
   = note: requested on the command line with `-D clippy::missing-mut`

error: variable must be `mut`
  --> tests/ui/iterator_step_by_zero.rs:26:9
   |
LL |     let x = 0..1;
   |         ^ help: make this variable mutable: `mut`

error: variable must be `mut`
  --> tests/ui/iterator_step_by_zero.rs:31:9
   |
LL |     let v1 = vec![1, 2, 3];
   |         ^ help: make this variable mutable: `mut`

error: item must be `pub`
  --> tests/ui/iterator_step_by_zero.rs:36:1
   |
LL | struct NotIterator;
   | ^ help: make this item public: `pub`

error: item must be `pub`
  --> tests/ui/iterator_step_by_zero.rs:37:1
   |
LL | impl NotIterator {
   | ^ help: make this item public: `pub`

error: function must be `unsafe`
  --> tests/ui/iterator_step_by_zero.rs:38:5
   |
LL |     fn step_by(&self, _: u32) {}
   |     ^
   |
help: make this function unsafe: `unsafe`
  --> tests/ui/iterator_step_by_zero.rs:38:5
   |
LL |     fn step_by(&self, _: u32) {}
   |     ^

error: parameter must be `mut`
  --> tests/ui/iterator_step_by_zero.rs:38:17
   |
LL |     fn step_by(&self, _: u32) {}
   |                 ^ help: make this parameter mutable: `mut`

error: references are not allowed
  --> tests/ui/iterator_step_by_zero.rs:38:16
   |
LL |     fn step_by(&self, _: u32) {}
   |                ^^^^^
   |
   = help: use a raw pointer instead: `*const`
   = note: requested on the command line with `-D clippy::reference-used`

error: lint `clippy::safe_fn` has been renamed to `clippy::safe_code`
   |
   = help: use the new name `clippy::safe_code`
   = note: requested on the command line with `-D clippy::safe_fn`
   = note: duplicate diagnostic emitted due to `-Z deduplicate-diagnostics=no`

error: missing `#![no_std]`
   |
   = help: make this crate `#![no_std]`
   = note: requested on the command line with `-D clippy::missing-no-std`

error: aborting due to 14 previous errors

