error: lint `clippy::safe_fn` has been renamed to `clippy::safe_code`
   |
   = help: use the new name `clippy::safe_code`
   = note: requested on the command line with `-D clippy::safe_fn`
   = note: `-D renamed-and-removed-lints` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(renamed_and_removed_lints)]`

error: lint `clippy::safe_fn` has been renamed to `clippy::safe_code`
   |
   = help: use the new name `clippy::safe_code`
   = note: requested on the command line with `-D clippy::safe_fn`
   = note: duplicate diagnostic emitted due to `-Z deduplicate-diagnostics=no`

error: item must be `pub`
  --> tests/ui/non_zero_suggestions_unfixable.rs:5:1
   |
LL | fn main() {
   | ^ help: make this item public: `pub`
   |
   = note: requested on the command line with `-D clippy::missing-pub`

error: function must be `unsafe`
  --> tests/ui/non_zero_suggestions_unfixable.rs:5:1
   |
LL | fn main() {
   | ^
   |
help: make this function unsafe: `unsafe`
  --> tests/ui/non_zero_suggestions_unfixable.rs:5:1
   |
LL | fn main() {
   | ^
   = note: `-D clippy::safe-code` implied by `-D clippy::safe-fn`
   = help: to override `-D clippy::safe-fn` add `#[allow(clippy::safe_code)]`

error: variable must be `mut`
  --> tests/ui/non_zero_suggestions_unfixable.rs:6:9
   |
LL |     let x: u64 = u64::from(NonZeroU32::new(5).unwrap().get());
   |         ^ help: make this variable mutable: `mut`
   |
   = note: requested on the command line with `-D clippy::missing-mut`

error: variable must be `mut`
  --> tests/ui/non_zero_suggestions_unfixable.rs:9:9
   |
LL |     let n = NonZeroU32::new(20).unwrap();
   |         ^ help: make this variable mutable: `mut`

error: variable must be `mut`
  --> tests/ui/non_zero_suggestions_unfixable.rs:10:9
   |
LL |     let y = u64::from(n.get());
   |         ^ help: make this variable mutable: `mut`

error: variable must be `mut`
  --> tests/ui/non_zero_suggestions_unfixable.rs:15:9
   |
LL |     let m = NonZeroU32::try_from(1).unwrap();
   |         ^ help: make this variable mutable: `mut`

error: variable must be `mut`
  --> tests/ui/non_zero_suggestions_unfixable.rs:16:9
   |
LL |     let _z: NonZeroU64 = m.into();
   |         ^ help: make this variable mutable: `mut`

error: item must be `pub`
  --> tests/ui/non_zero_suggestions_unfixable.rs:19:1
   |
LL | fn return_non_zero(x: u64, y: NonZeroU32) -> u64 {
   | ^ help: make this item public: `pub`

error: function must be `unsafe`
  --> tests/ui/non_zero_suggestions_unfixable.rs:19:1
   |
LL | fn return_non_zero(x: u64, y: NonZeroU32) -> u64 {
   | ^
   |
help: make this function unsafe: `unsafe`
  --> tests/ui/non_zero_suggestions_unfixable.rs:19:1
   |
LL | fn return_non_zero(x: u64, y: NonZeroU32) -> u64 {
   | ^

error: parameter must be `mut`
  --> tests/ui/non_zero_suggestions_unfixable.rs:19:20
   |
LL | fn return_non_zero(x: u64, y: NonZeroU32) -> u64 {
   |                    ^ help: make this parameter mutable: `mut`

error: parameter must be `mut`
  --> tests/ui/non_zero_suggestions_unfixable.rs:19:28
   |
LL | fn return_non_zero(x: u64, y: NonZeroU32) -> u64 {
   |                            ^ help: make this parameter mutable: `mut`

error: item must be `pub`
  --> tests/ui/non_zero_suggestions_unfixable.rs:24:1
   |
LL | fn some_fn_that_only_takes_u64(_: u64) {}
   | ^ help: make this item public: `pub`

error: function must be `unsafe`
  --> tests/ui/non_zero_suggestions_unfixable.rs:24:1
   |
LL | fn some_fn_that_only_takes_u64(_: u64) {}
   | ^
   |
help: make this function unsafe: `unsafe`
  --> tests/ui/non_zero_suggestions_unfixable.rs:24:1
   |
LL | fn some_fn_that_only_takes_u64(_: u64) {}
   | ^

error: lint `clippy::safe_fn` has been renamed to `clippy::safe_code`
   |
   = help: use the new name `clippy::safe_code`
   = note: requested on the command line with `-D clippy::safe_fn`
   = note: duplicate diagnostic emitted due to `-Z deduplicate-diagnostics=no`

error: missing `#![no_std]`
   |
   = help: make this crate `#![no_std]`
   = note: requested on the command line with `-D clippy::missing-no-std`

error: aborting due to 17 previous errors

