error: lint `clippy::safe_fn` has been renamed to `clippy::safe_code`
   |
   = help: use the new name `clippy::safe_code`
   = note: requested on the command line with `-D clippy::safe_fn`
   = note: `-D renamed-and-removed-lints` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(renamed_and_removed_lints)]`

error: lint `clippy::safe_fn` has been renamed to `clippy::safe_code`
   |
   = help: use the new name `clippy::safe_code`
   = note: requested on the command line with `-D clippy::safe_fn`
   = note: duplicate diagnostic emitted due to `-Z deduplicate-diagnostics=no`

error: item must be `pub`
  --> tests/ui/doc/doc_include_without_cfg.rs:12:1
   |
LL | macro_rules! man_link {
   | ^ help: make this item public: `pub`
   |
   = note: requested on the command line with `-D clippy::missing-pub`

error: item must be `pub`
  --> tests/ui/doc/doc_include_without_cfg.rs:19:1
   |
LL | macro_rules! tst {
   | ^ help: make this item public: `pub`

error: item must be `pub`
  --> tests/ui/doc/doc_include_without_cfg.rs:22:9
   |
LL |           fn blue() {
   |           ^ help: make this item public: `pub`
...
LL | / tst! {
LL | |     /// This is a test with no included file
LL | | }
   | |_- in this macro invocation
   |
   = note: this error originates in the macro `tst` (in Nightly builds, run with -Z macro-backtrace for more info)

error: function must be `unsafe`
  --> tests/ui/doc/doc_include_without_cfg.rs:22:9
   |
LL |           fn blue() {
   |           ^
...
LL | / tst! {
LL | |     /// This is a test with no included file
LL | | }
   | |_- in this macro invocation
   |
help: make this function unsafe: `unsafe`
  --> tests/ui/doc/doc_include_without_cfg.rs:22:9
   |
LL |           fn blue() {
   |           ^
...
LL | / tst! {
LL | |     /// This is a test with no included file
LL | | }
   | |_- in this macro invocation
   = note: `-D clippy::safe-code` implied by `-D clippy::safe-fn`
   = help: to override `-D clippy::safe-fn` add `#[allow(clippy::safe_code)]`
   = note: this error originates in the macro `tst` (in Nightly builds, run with -Z macro-backtrace for more info)

error: item must be `pub`
  --> tests/ui/doc/doc_include_without_cfg.rs:40:1
   |
LL | fn main() {
   | ^ help: make this item public: `pub`

error: function must be `unsafe`
  --> tests/ui/doc/doc_include_without_cfg.rs:40:1
   |
LL | fn main() {
   | ^
   |
help: make this function unsafe: `unsafe`
  --> tests/ui/doc/doc_include_without_cfg.rs:40:1
   |
LL | fn main() {
   | ^

error: lint `clippy::safe_fn` has been renamed to `clippy::safe_code`
   |
   = help: use the new name `clippy::safe_code`
   = note: requested on the command line with `-D clippy::safe_fn`
   = note: duplicate diagnostic emitted due to `-Z deduplicate-diagnostics=no`

error: missing `#![no_std]`
   |
   = help: make this crate `#![no_std]`
   = note: requested on the command line with `-D clippy::missing-no-std`

error: aborting due to 10 previous errors

