error: lint `clippy::safe_fn` has been renamed to `clippy::safe_code`
   |
   = help: use the new name `clippy::safe_code`
   = note: requested on the command line with `-D clippy::safe_fn`
   = note: `-D renamed-and-removed-lints` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(renamed_and_removed_lints)]`

error: lint `clippy::safe_fn` has been renamed to `clippy::safe_code`
   |
   = help: use the new name `clippy::safe_code`
   = note: requested on the command line with `-D clippy::safe_fn`
   = note: duplicate diagnostic emitted due to `-Z deduplicate-diagnostics=no`

error: lint `clippy::safe_fn` has been renamed to `clippy::safe_code`
   |
   = help: use the new name `clippy::safe_code`
   = note: requested on the command line with `-D clippy::safe_fn`
   = note: duplicate diagnostic emitted due to `-Z deduplicate-diagnostics=no`

error: item must be `pub`
  --> tests/ui/items_after_test_module/in_submodule.rs:3:1
   |
LL | mod submodule;
   | ^ help: make this item public: `pub`
   |
   = note: requested on the command line with `-D clippy::missing-pub`

error: item must be `pub`
  --> tests/ui/items_after_test_module/auxiliary/submodule.rs:2:1
   |
LL | mod tests {}
   | ^ help: make this item public: `pub`

error: item must be `pub`
  --> tests/ui/items_after_test_module/auxiliary/submodule.rs:4:1
   |
LL | fn in_submodule() {}
   | ^ help: make this item public: `pub`

error: function must be `unsafe`
  --> tests/ui/items_after_test_module/auxiliary/submodule.rs:4:1
   |
LL | fn in_submodule() {}
   | ^
   |
help: make this function unsafe: `unsafe`
  --> tests/ui/items_after_test_module/auxiliary/submodule.rs:4:1
   |
LL | fn in_submodule() {}
   | ^
   = note: `-D clippy::safe-code` implied by `-D clippy::safe-fn`
   = help: to override `-D clippy::safe-fn` add `#[allow(clippy::safe_code)]`

error: item must be `pub`
  --> tests/ui/items_after_test_module/in_submodule.rs:6:1
   |
LL | mod tests {
   | ^ help: make this item public: `pub`

error: item must be `pub`
  --> tests/ui/items_after_test_module/in_submodule.rs:8:5
   |
LL |     #[test]
   |     ------- in this procedural macro expansion
LL |     fn t() {}
   |     ^

error: item must be `pub`
  --> tests/ui/items_after_test_module/in_submodule.rs:8:5
   |
LL |     fn t() {}
   |     ^ help: make this item public: `pub`

error: function must be `unsafe`
  --> tests/ui/items_after_test_module/in_submodule.rs:8:5
   |
LL |     fn t() {}
   |     ^
   |
help: make this function unsafe: `unsafe`
  --> tests/ui/items_after_test_module/in_submodule.rs:8:5
   |
LL |     fn t() {}
   |     ^

error: function must be `unsafe`
   |
   = help: make this function unsafe: `unsafe`

error: references are not allowed
   |
   = help: use a raw borrowing instead: `&raw const`
   = note: requested on the command line with `-D clippy::reference-used`

error: references are not allowed
  --> tests/ui/items_after_test_module/in_submodule.rs:8:5
   |
LL |     #[test]
   |     ------- in this procedural macro expansion
LL |     fn t() {}
   |     ^^^^^^^^^
   |
   = help: use a raw borrowing instead: `&raw const`

error: lint `clippy::safe_fn` has been renamed to `clippy::safe_code`
   |
   = help: use the new name `clippy::safe_code`
   = note: requested on the command line with `-D clippy::safe_fn`
   = note: duplicate diagnostic emitted due to `-Z deduplicate-diagnostics=no`

error: missing `#![no_std]`
   |
   = help: make this crate `#![no_std]`
   = note: requested on the command line with `-D clippy::missing-no-std`

error: aborting due to 16 previous errors

